---
# MySQL install, based partly on process at-
#  http://stackoverflow.com/questions/16444306/ansible-idempotent-mysql-installation-playbook
- name: mariadb server is installed
  apt: package=mariadb-server state=present update_cache=no
  tags: mariadb

- name: python-mysqldb is installed
  apt: package=python-mysqldb state=present update_cache=no
  tags: mariadb

- name: mariadb server is enabled
  service: name=mysql enabled=yes state=started
  tags: mariadb

- name: mariadb root password is set for all root accounts
  mysql_user: name=root host={{ item }} password={{ mariadb_root_password }} priv=*.*:ALL,GRANT state=present
  with_items:
    - "{{ ansible_hostname }}"
    - ::1
    - localhost
  tags: mariadb

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: mariadb

# The '127.0.0.1' account does not always exist, so we use the new root password
# to either create or reset it.
- name: mariadb root password is set for all root accounts
  mysql_user: name=root host={{ item }} password={{ mariadb_root_password }} priv=*.*:ALL,GRANT state=present
  with_items:
    - 127.0.0.1
  tags: mariadb

- name: anonymous mysql server user for localhost is deleted
  action: mysql_user user="" state=absent
  tags: mariadb

- name: mysql test database is removed
  action: mysql_db db=test state=absent
  tags: mariadb

# TODO per-database user accounts to reduce impact of database compromise
- name: application DB users are created
  mysql_user: name={{ app_db_user }} password={{ app_db_pass }} priv=*.*:ALL host="localhost" state=present
  tags: mariadb

- name: database backup is uploaded to server
  copy: src=backup/wmau.sql.gz dest=/var/backups/wmau-db.sql.gz owner=root group=root mode=0600
  when: restore | default('false') | bool
  tags: mariadb

# TODO could to a per-database import if /var/lib/mysql/(name)/ does not exist.
- name: databases are restored from backup
  shell: gunzip -c /var/backups/wmau-db.sql.gz | mysql
  when: restore | default('false') | bool
  tags: mariadb
