---
- name: ntp is installed
  apt: package=ntp state=present update_cache=no
  tags: ntp

- name: ntp is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp

- name: timezone is UTC
  when: ansible_date_time.tz != 'UTC'
  command: timedatectl set-timezone 'UTC'
  tags: ntp
