---
- name: setting up /etc/ssh/sshd_config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart sshd
  tags: sshd

- name: sshd is running and enabled
  service: name=sshd state=running enabled=yes
  tags: sshd
